trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- download: current
  artifact: drop
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'your-subscription'
    appName: 'your-web-app'
    package: $(System.ArtifactsDirectory)/drop/*.zip
