trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@2
  inputs:
    versionSpec: '16.x'
- script: |
    npm install
    npm test
  displayName: 'Install dependencies and run tests'
- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop
